### ISSUE TITLE
Undefined Method Exception

### ISSUE THREAD

**Issue by smadaman** [madesst/MadesstDoctrineGenerationBundle#1]
Hi,

I have been using your bundle for quite a while now and it is fantastic!

Though recenlty, and I believe it is after updating some vendors that I get an error now when trying to generate, it is

> backing up User.php to User.php~
> PHP Fatal error:  Call to undefined method Doctrine\ORM\Mapping\ClassMetadata::getUserClassMetadata() in C:\Bitnami\wamp
> stack-5.4.35-0\apps\austockphoto\htdocs\vendor\madesst\doctrine-generation-bundle\Madesst\DoctrineGenerationBundle\Comma
> nd\GenerateEntitiesDoctrineCommand.php on line 85

  [Symfony\Component\Debug\Exception\UndefinedMethodException]
  Attempted to call method "getUserClassMetadata" on class "Doctrine\ORM\Mapping\ClassMetadata".

  doctrine:generate:entities [--path="..."] [--no-backup] [--propel-style] name

Would you please be able to help me with this and why this might be happening,

Cheers

**Comment by madesst** [comment]
Hi! Sorry for the long waiting time, I did not think that someone is using this bundle.

Thank you for this issue.
Version amended for normal operation with an updated doctrine already in master.

**Comment by madesst** [comment]
https://github.com/madesst/MadesstDoctrineGenerationBundle/tree/v1.1.0

**Comment by smadaman** [comment]
Thanks very much.

I love this bundle

Cheers
